name: Deploy to IBM Container Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_ORG: ${{ secrets.IBM_CLOUD_ORG }}
  IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
  IBM_CLOUD_SPACE: ${{ secrets.IBM_CLOUD_SPACE }}
  ICR_NAMESPACE: ${{ secrets.ICR_NAMESPACE }}
  REGISTRY_HOSTNAME: us.icr.io
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}


jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2

      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud cf install
          ibmcloud plugin install -f container-registry

      # Build the Docker image
      - name: Build with Docker
        run: |
          docker build -t $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      # Authenticate with IBM Cloud CLI, and push the image to IBM Container Registry
      - name: Authenticate with IBM Cloud CLI and push the Docker image to ICR
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Default
          ibmcloud target -o ${IBM_CLOUD_ORG} -s ${IBM_CLOUD_SPACE} --cf
          ibmcloud cr region-set "${IBM_CLOUD_REGION}"
          ibmcloud cr login
          docker push $REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA
